apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: quarkus-native-proto
    newName: quarkus-native-proto
    newTag: 0.1.0

patches:
  - path: patch-local.yaml
    target:
      kind: Deployment
      name: quarkus-native-proto
